clients:
  - 2
  - 1

training:
  num_epochs: 20
  num_rounds: 4
  batch_size: 1
  learning_rate: 0.001
  optimizer: 'SGD' # Adam or SGD
  momentum: 0.9
  num_workers: 0

model:
  edge: 'AlexNet_EDGE'
  server: 'AlexNet_SERVER'
  save_path: 'cifar_net.pth'
  save_model: true
  pretrained_path: './yolo11n.pt'

cut_layer: 
  - 10
  - 10

dataset:
  - datasets/coco8.yaml
  - datasets/coco8.yaml

rabbitmq:
  host: 'rabbitmq'
  port: 5672
  username: 'guest'
  password: 'guest'