clients:
  - 4
  - 1

training:
  num_epochs: 2
  num_rounds: 4
  batch_size: 8
  learning_rate: 0.001
  optimizer: 'Adam' # Adam or SGD
  momentum: 0.9
  num_workers: 0

model:
  edge: 'AlexNet_EDGE'
  server: 'AlexNet_SERVER'
  save_path: 'cifar_net.pth'
  save_model: true
  pretrained_path: './yolo11n.pt'

cut_layer: 
  - 5
  - 10
  - 5
  - 10

dataset:
  - datasets/subdataset/livingroom_2_iid/client_1.yaml
  - datasets/subdataset/livingroom_2_iid/client_2.yaml
  - datasets/subdataset/livingroom_2_iid/client_3.yaml
  - datasets/subdataset/livingroom_2_iid/client_4.yaml

rabbitmq:
  host: 'rabbitmq'
  port: 5672
  username: 'guest'
  password: 'guest'
